from app.schemas.trend import TrendAnalysisInput, TrendAnalysisResult


def generate_mock_trend_result(input_data: TrendAnalysisInput) -> TrendAnalysisResult:
    category = input_data.category
    target_user = input_data.target_user
    scene = input_data.scene
    style = input_data.style

    return TrendAnalysisResult.model_validate(
        {
            "summary": f"{category} 正在从单一款式竞争转向场景化、功能化和内容传播兼具的设计竞争。",
            "opportunity": f"{target_user} 对 {scene} 的穿着需求更细分，适合用高识别风格和明确卖点打造爆款。",
            "risk": "过度堆叠设计元素会提高成本，并削弱日常搭配接受度。",
            "style_directions": [
                {
                    "id": "style_light_tech",
                    "name": "轻机能通勤",
                    "description": "保留机能细节，但整体轮廓克制干净。",
                    "score": 94,
                    "reason": "兼顾功能卖点和日常穿搭，适合快速验证市场。",
                    "tags": ["通勤", "机能"],
                },
                {
                    "id": "style_cool_sport",
                    "name": "冷感运动",
                    "description": "用清爽配色和运动线条强调轻盈。",
                    "score": 88,
                    "reason": "更适合夏季视觉传播和年轻用户。",
                    "tags": ["运动", "清凉"],
                },
                {
                    "id": "style_quiet_luxury",
                    "name": "静奢户外",
                    "description": "用低饱和色和高级面料弱化装备感。",
                    "score": 83,
                    "reason": "有利于提升客单价和高端系列延展。",
                    "tags": ["高端", "户外"],
                },
                {
                    "id": "style_soft_utility",
                    "name": "柔和实用主义",
                    "description": "用柔化线条和实用细节平衡功能感与亲和力。",
                    "score": 85,
                    "reason": "适合从通勤扩展到周末短途，降低高机能风格的穿搭门槛。",
                    "tags": ["实用", "柔和"],
                },
            ],
            "silhouettes": [
                {
                    "id": "silhouette_cropped_loose",
                    "name": "短款微宽松",
                    "description": "短款比例结合适度余量，利落且包容。",
                    "score": 91,
                    "reason": "适合高腰裤裙，视觉显比例。",
                    "tags": ["短款", "宽松"],
                },
                {
                    "id": "silhouette_boxy",
                    "name": "Boxy 直身",
                    "description": "肩部有量，下摆收净，降低户外膨胀感。",
                    "score": 86,
                    "reason": "覆盖更多身形，也容易做系列化。",
                    "tags": ["直身", "包容"],
                },
                {
                    "id": "silhouette_longline",
                    "name": "中长防护",
                    "description": "提升覆盖面积，强化功能属性。",
                    "score": 78,
                    "reason": "功能明确，但时髦度和搭配轻盈感稍弱。",
                    "tags": ["中长", "防护"],
                },
                {
                    "id": "silhouette_drawstring_hem",
                    "name": "抽绳收摆",
                    "description": "通过下摆抽绳在利落短款和防风包裹之间切换。",
                    "score": 84,
                    "reason": "提升版型可调性，也让详情页更容易表达穿法差异。",
                    "tags": ["可调", "收摆"],
                },
            ],
            "core_structures": [
                {
                    "id": "structure_sun_hood",
                    "name": "高领防护帽",
                    "description": "帽领一体增强头颈覆盖。",
                    "score": 93,
                    "reason": "用户感知强，详情页表达直接。",
                    "tags": ["防护", "帽型"],
                },
                {
                    "id": "structure_air_vents",
                    "name": "背部隐形透气",
                    "description": "后背加入隐藏通风结构。",
                    "score": 89,
                    "reason": "解决夏季外套闷热痛点。",
                    "tags": ["透气", "舒适"],
                },
                {
                    "id": "structure_packable",
                    "name": "便携收纳袋",
                    "description": "内置收纳结构，适合出行。",
                    "score": 84,
                    "reason": "强化旅行和通勤备用场景。",
                    "tags": ["便携", "旅行"],
                },
                {
                    "id": "structure_curve_cut",
                    "name": "弧形分割线",
                    "description": "用曲线切割塑造速度感。",
                    "score": 82,
                    "reason": "提升基础款设计识别度。",
                    "tags": ["线条", "设计感"],
                },
            ],
            "color_palette": [
                {
                    "id": "color_glacier_white",
                    "name": "冰川白",
                    "hex": "#F5F7F2",
                    "role": "primary",
                    "score": 95,
                    "reason": "清爽轻量，是防晒和夏季品类的高转化基础色。",
                },
                {
                    "id": "color_mist_blue",
                    "name": "雾感蓝",
                    "hex": "#A8D8EA",
                    "role": "secondary",
                    "score": 88,
                    "reason": "强化冷感科技视觉。",
                },
                {
                    "id": "color_lime_signal",
                    "name": "信号青柠",
                    "hex": "#B7F566",
                    "role": "accent",
                    "score": 81,
                    "reason": "适合拉链、抽绳和局部标识点缀。",
                },
                {
                    "id": "color_graphite",
                    "name": "石墨灰",
                    "hex": "#3E4652",
                    "role": "secondary",
                    "score": 76,
                    "reason": "平衡浅色的运动感和耐脏诉求。",
                },
            ],
            "fabric_trends": [
                {
                    "id": "fabric_uv_shell",
                    "name": "轻量 UPF 壳层",
                    "description": "薄、挺、抗 UV，保持干净廓形。",
                    "score": 96,
                    "reason": "直接对应核心购买理由。",
                    "tags": ["UPF", "轻量"],
                },
                {
                    "id": "fabric_cool_touch",
                    "name": "接触冷感纤维",
                    "description": "强调穿着瞬间凉感。",
                    "score": 90,
                    "reason": "适合短视频和详情页体感表达。",
                    "tags": ["冷感", "夏季"],
                },
                {
                    "id": "fabric_wrinkle_free",
                    "name": "抗皱旅行面料",
                    "description": "收纳后恢复平整。",
                    "score": 82,
                    "reason": "增强通勤和出行场景。",
                    "tags": ["抗皱", "旅行"],
                },
                {
                    "id": "fabric_matte_ripstop",
                    "name": "哑光格纹防撕裂",
                    "description": "轻薄格纹肌理带来户外性能感但不显厚重。",
                    "score": 84,
                    "reason": "能提高近景质感和耐用感，适合做中高价位款。",
                    "tags": ["防撕裂", "哑光"],
                },
            ],
            "selling_points": [
                {
                    "id": "sp_upf",
                    "name": "UPF 50+ 防晒",
                    "description": "可量化核心防护指标。",
                    "score": 97,
                    "reason": "搜索和转化价值最高。",
                    "tags": ["防护", "功能"],
                },
                {
                    "id": "sp_breathable",
                    "name": "不闷热透气",
                    "description": "针对夏季外套核心阻力。",
                    "score": 92,
                    "reason": "直接降低购买顾虑。",
                    "tags": ["透气", "舒适"],
                },
                {
                    "id": "sp_commute_ready",
                    "name": "通勤可搭",
                    "description": "强调不是纯户外装备。",
                    "score": 88,
                    "reason": "扩大日常穿着频次。",
                    "tags": ["通勤", "百搭"],
                },
                {
                    "id": "sp_packable",
                    "name": "轻巧便携",
                    "description": "适合包内携带和旅行。",
                    "score": 84,
                    "reason": "提升场景价值。",
                    "tags": ["便携", "旅行"],
                },
            ],
            "recommended_directions": [
                {
                    "id": "direction_high_potential",
                    "name": "高爆款通勤方案",
                    "positioning": f"{scene} {category}",
                    "target_user": target_user,
                    "style_ids": ["style_light_tech"],
                    "silhouette_ids": ["silhouette_cropped_loose"],
                    "structure_ids": ["structure_sun_hood", "structure_air_vents"],
                    "color_ids": ["color_glacier_white", "color_mist_blue"],
                    "fabric_ids": ["fabric_uv_shell", "fabric_cool_touch"],
                    "selling_point_ids": ["sp_upf", "sp_breathable", "sp_commute_ready"],
                    "design_summary": f"面向 {target_user} 的 {category}，主打轻机能通勤与高感知防护。",
                    "popularity_score": 91,
                    "cost_complexity": "medium",
                    "ai_prompt": f"{category}，{target_user}，{scene}，{style}，短款微宽松，冰川白与雾感蓝，高领防护帽，背部透气，轻量 UPF 面料。",
                },
                {
                    "id": "direction_visual_sport",
                    "name": "冷感运动视觉方案",
                    "positioning": f"年轻化冷感运动 {category}",
                    "target_user": target_user,
                    "style_ids": ["style_cool_sport"],
                    "silhouette_ids": ["silhouette_boxy"],
                    "structure_ids": ["structure_curve_cut", "structure_air_vents"],
                    "color_ids": ["color_mist_blue", "color_lime_signal"],
                    "fabric_ids": ["fabric_cool_touch", "fabric_uv_shell"],
                    "selling_point_ids": ["sp_breathable", "sp_upf"],
                    "design_summary": "用冷感配色和速度线条打造更强社媒传播视觉。",
                    "popularity_score": 86,
                    "cost_complexity": "medium",
                    "ai_prompt": f"{category}，冷感运动风，雾感蓝，信号青柠点缀，Boxy 廓形，弧形分割线，轻量透气。",
                },
                {
                    "id": "direction_premium_outdoor",
                    "name": "静奢轻户外方案",
                    "positioning": f"高端轻户外 {category}",
                    "target_user": target_user,
                    "style_ids": ["style_quiet_luxury"],
                    "silhouette_ids": ["silhouette_longline"],
                    "structure_ids": ["structure_packable", "structure_sun_hood"],
                    "color_ids": ["color_graphite", "color_glacier_white"],
                    "fabric_ids": ["fabric_wrinkle_free", "fabric_uv_shell"],
                    "selling_point_ids": ["sp_commute_ready", "sp_packable", "sp_upf"],
                    "design_summary": "低饱和色和抗皱面料提升高端通勤属性。",
                    "popularity_score": 80,
                    "cost_complexity": "high",
                    "ai_prompt": f"{category}，静奢轻户外风，石墨灰，中长廓形，抗皱旅行面料，便携收纳，高领防护。",
                },
                {
                    "id": "direction_packable_weekend",
                    "name": "周末轻旅行便携方案",
                    "positioning": f"可收纳轻户外 {category}",
                    "target_user": target_user,
                    "style_ids": ["style_soft_utility"],
                    "silhouette_ids": ["silhouette_drawstring_hem"],
                    "structure_ids": ["structure_packable", "structure_sun_hood"],
                    "color_ids": ["color_glacier_white", "color_lime_signal"],
                    "fabric_ids": ["fabric_matte_ripstop", "fabric_uv_shell"],
                    "selling_point_ids": ["sp_packable", "sp_upf", "sp_commute_ready"],
                    "design_summary": f"面向 {target_user} 的周末短途场景，强调可收纳、可调节与轻防护。",
                    "popularity_score": 84,
                    "cost_complexity": "medium",
                    "ai_prompt": f"{category}，周末轻旅行风，抽绳收摆，哑光格纹防撕裂面料，冰川白搭配信号青柠，便携收纳，UPF 50+。",
                },
            ],
            "base_prompt": f"{category}，{target_user}，{scene}，{style}，高级服装产品设计稿。",
        }
    )
