import type { MyDesignPlan, TrendAnalysisInput, TrendAnalysisResponse } from "@/lib/types/trend";

export const defaultInput: TrendAnalysisInput = {
  category: "女款防晒夹克",
  target_user: "18-30 岁城市通勤女性",
  scene: "通勤 / 轻户外 / 周末短途",
  style: "轻机能、高级运动、冷感未来",
};

export const mockAnalysis: TrendAnalysisResponse = {
  analysis_id: "mock-analysis-styleforge-001",
  status: "success",
  input: defaultInput,
  created_at: "2026-05-14T22:30:00+08:00",
  result: {
    summary: "防晒品类正在从单一功能外套升级为城市轻户外的造型入口，用户更关注清凉视觉、通勤适配和可量化防护。",
    opportunity: "冷感色系、轻量面料和可拆卸防晒结构能同时承接功能搜索与穿搭传播。",
    risk: "过度户外化会降低通勤接受度，过多结构件也会推高成本和尺码适配风险。",
    style_directions: [
      {
        id: "style_light_tech",
        name: "轻机能通勤",
        description: "保留功能细节，但整体轮廓克制干净。",
        score: 94,
        reason: "兼容电商搜索、日常穿搭和轻户外内容表达。",
        tags: ["通勤", "机能"],
      },
      {
        id: "style_cool_sport",
        name: "冷感运动",
        description: "使用清爽配色和运动分割线强调轻盈。",
        score: 88,
        reason: "适合夏季防晒主视觉和年轻客群。",
        tags: ["清凉", "运动"],
      },
      {
        id: "style_quiet_lux",
        name: "静奢户外",
        description: "低饱和色和高级面料质感弱化装备感。",
        score: 83,
        reason: "利于客单价提升和高端款式延展。",
        tags: ["高端", "质感"],
      },
      {
        id: "style_soft_utility",
        name: "柔和实用主义",
        description: "用柔化线条和实用细节平衡功能感与亲和力。",
        score: 85,
        reason: "适合从通勤扩展到周末短途，降低高机能风格的穿搭门槛。",
        tags: ["实用", "柔和"],
      },
    ],
    silhouettes: [
      {
        id: "silhouette_cropped",
        name: "短款微宽松",
        description: "利落短款配合轻微余量，适合高腰裤裙。",
        score: 91,
        reason: "更容易形成显比例的搭配传播。",
        tags: ["短款", "显比例"],
      },
      {
        id: "silhouette_boxy",
        name: "Boxy 廓形",
        description: "肩部有量但下摆收净，弱化户外膨胀感。",
        score: 86,
        reason: "适合多身形覆盖。",
        tags: ["包容", "利落"],
      },
      {
        id: "silhouette_longline",
        name: "中长防护",
        description: "覆盖臀部，提高防晒面积。",
        score: 78,
        reason: "功能明确但时髦度稍弱。",
        tags: ["覆盖", "功能"],
      },
      {
        id: "silhouette_drawstring_hem",
        name: "抽绳收摆",
        description: "通过下摆抽绳在利落短款和防风包裹之间切换。",
        score: 84,
        reason: "提升版型可调性，也让详情页更容易表达穿法差异。",
        tags: ["可调", "收摆"],
      },
    ],
    core_structures: [
      {
        id: "structure_sun_hood",
        name: "高领防晒帽",
        description: "帽口和领部一体化，增强颈部覆盖。",
        score: 93,
        reason: "用户感知强，视觉也有记忆点。",
        tags: ["防晒", "头颈保护"],
      },
      {
        id: "structure_air_vents",
        name: "背部隐形透气",
        description: "后背加入隐藏式通风片。",
        score: 89,
        reason: "解决夏季防晒闷热痛点。",
        tags: ["透气", "舒适"],
      },
      {
        id: "structure_packable",
        name: "便携收纳袋",
        description: "口袋内置收纳结构，适合出行。",
        score: 84,
        reason: "提升场景覆盖和详情页卖点。",
        tags: ["便携", "出行"],
      },
      {
        id: "structure_curve_cut",
        name: "弧形分割线",
        description: "用曲线切割塑造速度感。",
        score: 82,
        reason: "让基础防晒衣更有设计识别。",
        tags: ["线条", "设计感"],
      },
    ],
    color_palette: [
      {
        id: "color_glacier_white",
        name: "冰川白",
        hex: "#F5F7F2",
        role: "primary",
        score: 95,
        reason: "清爽、轻量，是防晒品类的高转化基础色。",
      },
      {
        id: "color_mist_blue",
        name: "雾感蓝",
        hex: "#A8D8EA",
        role: "secondary",
        score: 88,
        reason: "强化冷感科技视觉。",
      },
      {
        id: "color_lime_signal",
        name: "信号青柠",
        hex: "#B7F566",
        role: "accent",
        score: 81,
        reason: "适合拉链、抽绳和局部标识。",
      },
      {
        id: "color_graphite",
        name: "石墨灰",
        hex: "#3E4652",
        role: "secondary",
        score: 76,
        reason: "平衡浅色的运动感和耐脏诉求。",
      },
    ],
    fabric_trends: [
      {
        id: "fabric_uv_shell",
        name: "轻量 UPF 壳层",
        description: "薄、挺、抗 UV，保持干净廓形。",
        score: 96,
        reason: "直接对应核心购买理由。",
        tags: ["UPF", "轻量"],
      },
      {
        id: "fabric_cool_touch",
        name: "接触冷感纤维",
        description: "强调穿着瞬间凉感。",
        score: 90,
        reason: "适合短视频和详情页体感表达。",
        tags: ["冷感", "夏季"],
      },
      {
        id: "fabric_wrinkle_free",
        name: "抗皱旅行面料",
        description: "收纳后恢复平整。",
        score: 82,
        reason: "增强通勤和出行场景。",
        tags: ["抗皱", "旅行"],
      },
      {
        id: "fabric_matte_ripstop",
        name: "哑光格纹防撕裂",
        description: "轻薄格纹肌理带来户外性能感但不显厚重。",
        score: 84,
        reason: "能提高近景质感和耐用感，适合做中高价位款。",
        tags: ["防撕裂", "哑光"],
      },
    ],
    selling_points: [
      {
        id: "sp_upf",
        name: "UPF 50+ 防晒",
        description: "可量化核心防护指标。",
        score: 97,
        reason: "搜索和转化价值最高。",
        tags: ["功能", "防护"],
      },
      {
        id: "sp_breathable",
        name: "不闷热透气",
        description: "针对夏季外套核心阻力。",
        score: 92,
        reason: "能直接降低购买顾虑。",
        tags: ["舒适", "夏季"],
      },
      {
        id: "sp_commute_ready",
        name: "通勤可搭",
        description: "强调不是纯户外装备。",
        score: 88,
        reason: "扩大日常穿着频次。",
        tags: ["通勤", "百搭"],
      },
      {
        id: "sp_packable",
        name: "轻巧便携",
        description: "适合包内携带和旅行。",
        score: 84,
        reason: "提升场景价值。",
        tags: ["便携", "旅行"],
      },
    ],
    recommended_directions: [
      {
        id: "direction_hot_commute",
        name: "高爆款通勤防晒夹克",
        positioning: "城市轻户外通勤防晒夹克",
        target_user: "18-30 岁城市通勤女性",
        style_ids: ["style_light_tech"],
        silhouette_ids: ["silhouette_cropped"],
        structure_ids: ["structure_sun_hood", "structure_air_vents"],
        color_ids: ["color_glacier_white", "color_mist_blue"],
        fabric_ids: ["fabric_uv_shell", "fabric_cool_touch"],
        selling_point_ids: ["sp_upf", "sp_breathable", "sp_commute_ready"],
        design_summary: "短款微宽松廓形，冰川白主色，结合高领防晒帽和背部透气结构。",
        popularity_score: 91,
        cost_complexity: "medium",
        ai_prompt: "女款城市轻户外防晒夹克，短款微宽松，冰川白与雾感蓝，高领防晒帽，背部隐形透气，UPF 50+，高级冷感科技风。",
      },
      {
        id: "direction_visual_sport",
        name: "冷感运动视觉款",
        positioning: "夏季冷感运动防晒外套",
        target_user: "年轻运动休闲用户",
        style_ids: ["style_cool_sport"],
        silhouette_ids: ["silhouette_boxy"],
        structure_ids: ["structure_curve_cut", "structure_air_vents"],
        color_ids: ["color_mist_blue", "color_lime_signal"],
        fabric_ids: ["fabric_cool_touch", "fabric_uv_shell"],
        selling_point_ids: ["sp_breathable", "sp_upf"],
        design_summary: "雾感蓝主视觉搭配青柠点缀，用弧形分割线制造速度感。",
        popularity_score: 86,
        cost_complexity: "medium",
        ai_prompt: "冷感运动女款防晒外套，雾感蓝，信号青柠点缀，Boxy 廓形，弧形分割线，轻量透气，未来运动风。",
      },
      {
        id: "direction_premium_outdoor",
        name: "静奢轻户外高端款",
        positioning: "高端通勤轻户外防晒外套",
        target_user: "高客单价通勤女性",
        style_ids: ["style_quiet_lux"],
        silhouette_ids: ["silhouette_longline"],
        structure_ids: ["structure_packable", "structure_sun_hood"],
        color_ids: ["color_graphite", "color_glacier_white"],
        fabric_ids: ["fabric_wrinkle_free", "fabric_uv_shell"],
        selling_point_ids: ["sp_commute_ready", "sp_packable", "sp_upf"],
        design_summary: "石墨灰中长款，低调结构与抗皱面料强化高级通勤属性。",
        popularity_score: 80,
        cost_complexity: "high",
        ai_prompt: "高端静奢女款轻户外防晒外套，石墨灰中长廓形，抗皱旅行面料，便携收纳，高领防晒帽，低调高级。",
      },
      {
        id: "direction_packable_weekend",
        name: "周末轻旅行便携款",
        positioning: "可收纳轻户外防晒夹克",
        target_user: "城市周末短途与旅行用户",
        style_ids: ["style_soft_utility"],
        silhouette_ids: ["silhouette_drawstring_hem"],
        structure_ids: ["structure_packable", "structure_sun_hood"],
        color_ids: ["color_glacier_white", "color_lime_signal"],
        fabric_ids: ["fabric_matte_ripstop", "fabric_uv_shell"],
        selling_point_ids: ["sp_packable", "sp_upf", "sp_commute_ready"],
        design_summary: "抽绳收摆结合便携收纳结构，兼顾周末短途、防晒防风和城市穿搭。",
        popularity_score: 84,
        cost_complexity: "medium",
        ai_prompt: "女款周末轻旅行防晒夹克，抽绳收摆，哑光格纹防撕裂面料，冰川白搭配信号青柠点缀，便携收纳，UPF 50+。",
      },
    ],
    base_prompt: "女款防晒夹克，18-30 岁城市通勤女性，通勤与轻户外场景，冷感高级科技风。",
  },
};

export const mockPlans: MyDesignPlan[] = mockAnalysis.result!.recommended_directions.map((direction) => ({
  id: direction.id,
  analysis_id: mockAnalysis.analysis_id,
  design_summary: direction.design_summary,
  style_description: direction.positioning,
  recommended_direction: direction.name,
  popularity_score: direction.popularity_score,
  ai_prompt: direction.ai_prompt,
  is_favorite: direction.id === "direction_hot_commute",
  warnings: direction.cost_complexity === "high" ? ["结构和面料成本较高，建议作为高端线开发。"] : [],
  selected_items: {
    analysis_id: mockAnalysis.analysis_id,
    selected_style_ids: direction.style_ids,
    selected_silhouette_ids: direction.silhouette_ids,
    selected_structure_ids: direction.structure_ids,
    selected_color_ids: direction.color_ids,
    selected_fabric_ids: direction.fabric_ids,
    selected_selling_point_ids: direction.selling_point_ids,
  },
}));
